### ISSUE TITLE
Feature request: Remove unnecessary white space

### ISSUE THREAD

**Issue by supukarmin** [detrohutt/babel-plugin-import-graphql#32]
The plugin should per default remove all the white space when importing. In some of my projects it could probably save up 20-30% of the build size, because everything is being minimized, except GraphQL, which makes GraphQL become relatively seen a really big part of the build.

You could just add this library: https://github.com/rse/graphql-query-compress and probably one line of code somewhere.

~~This would make the library a must-have.~~

**Edit**: I just realized that this plugin is is really inlining comepletely (I thought it would include some helper function for AST creation). However, it could still be a nice feature to reduce the build size.

**Comment by detrohutt** [comment]
If I did start stripping comments I'd need to make it optional and off by default to prevent it being a breaking change. It's unlikely but possible someone is extracting or using the comments in some way from the imported query.

I'd *consider* doing this, but on first thought, I'm leaning towards declining. It's unfortunately not going to be a one-liner because of what I mentioned above. Additionally, it's not something I'd want to add code for myself, and the package you linked isn't all that popular/field-tested, so I'd be afraid it'd cause edge-case problems that I'd then be responsible for addressing. His repo seems fairly inactive, with several unaddressed PR's from February, so if it did cause problems I'd be worried I wouldn't be able to get anything done about it in a timely fashion.

The general expectation I had in mind when creating this is that if bundle size was a priority, then `gql` would probably be used directly instead of my plugin, whereas if processing power was more of a concern (mobile devices on wifi?), then the preprocessing my plugin does would justify the cost of the extra bundle size, especially when you consider the added pleasantness and convenience of separate files for your GraphQL.

I'm not sure how you structure your files, but if you're importing a lot of your GraphQL operations/fragments in more than one place each, there's an alternative that might help reduce bundle size. You could import and re-export them all in one or more `.js` files, doing the final imports from a `.js` file. Depending on your file structure and/or your build pipeline (rollup, etc), this may or may not help with bundle size.

**Comment by detrohutt** [comment]
One point I forgot to make is that any type of AST is extremely verbose by nature, so I'd expect any reduction in size by removing whitespace and comments to generally be pretty marginal. If you'd be willing to run some benchmarks on some `.graphql` files of different sizes, with/without comments, and let me know what the actual size reductions are, I may reconsider my stance.

Also, one option would be for me to create an option called i.e. `processAtRuntime`, which instead of inlining the AST object would inline something like:

```javascript
import gql from 'graphql-tag';
var importName = gql`${importSource}`;
```

However, this would be a pretty big undertaking to implement while keeping backwards compatibility. In practice, both `importName` and `importSource` would have a lot of logic involved to support all the import types and options I currently expose. It would also require me to make `gql` an optionalDependency.

**Comment by detrohutt** [comment]
@supukarmin Looking back over this, most of what I said was incorrect or doesn't make sense. Sorry about that, I should probably start sleeping more lol. Anyway, I've implemented a change to remove most whitespace, resulting in about 30% smaller output size. It will take effect in version `2.5.0`. Thanks for the tip! Would you mind if I add your name in the CHANGELOG/Release notes?

**Comment by detrohutt** [comment]
Sure, I’ll see if I can get that working soon. I’ll let you know how it turns out. :)

**Comment by supukarmin** [comment]
@detrohutt Looks great, thank you for the update.
